#!/bin/sh

packs_dir=$HOME/.config/emacs/packs

echo "clearing out live packs"
find "$packs_dir/stable" \
     -maxdepth 1 \
     ! -name 'stable' \
     ! -name '.gitkeep' \
     -type d \
     -exec rm -Rf {} \;

echo "copying content from dev packs"
cp -pRL $packs_dir/dev/* $packs_dir/stable/

echo "removing dev detritus"
rm -rf "$packs_dir/stable/**/vendor"
rm -rf "$packs_dir/stable/**/.git*"
#rm -rf "$packs_dir/stable/**/*.elc"
